# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-new-no-sidebar',
                'doc_host': 'https://dsm-72.github.io',
                'git_url': 'https://github.com/dsm-72/nbdev-new-no-sidebar',
                'lib_path': 'nbdev_new_no_sidebar'},
  'syms': {'nbdev_new_no_sidebar.core': {'nbdev_new_no_sidebar.core.foo': ('core.html#foo', 'nbdev_new_no_sidebar/core.py')}}}
